config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :friends
  # get 'home/index'
  # root 'home#index'
  root 'friends#index'
  get 'home/about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friend.rb
class Friend < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :friends
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[show edit update destroy]
  # Except a user is authenticated, don't let them do anything except see the index&show page
  before_action :authenticate_user!, except: %i[index show]
  # Check for the correct user b4 edit,update,destroy pages/a user that create a friend should be the one to del it.
  before_action :correct_user, only: %i[edit update destroy]
  # GET /friends
  # GET /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1
  # GET /friends/1.json
  def show; end

  # GET /friends/new
  def new
    # @friend = Friend.new
    # Associate the current user to the friend
    @friend = current_user.friends.build
  end

  # GET /friends/1/edit
  def edit; end

  # POST /friends
  # POST /friends.json
  def create
    # @friend = Friend.new(friend_params)
    @friend = current_user.friends.build(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to @friend, notice: 'Friend was successfully created.' }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1
  # PATCH/PUT /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to @friend, notice: 'Friend was successfully updated.' }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1
  # DELETE /friends/1.json
  def destroy
    @friend.destroy
    respond_to do |format|
      format.html { redirect_to friends_url, notice: 'Friend was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def correct_user
    # The id is the PK assigned to the friends table by devise gem
    # A user has many friends
    @friend = current_user.friends.find_by(id: params[:id])
    redirect_to friends_path, notice: 'Not authorised for this action' if @friend.nil?
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_friend
    @friend = Friend.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def friend_params
    params.require(:friend).permit(:first_name, :last_name, :email, :phone, :twitter, :user_id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end

  def about; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/friends/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <strong><%= notice %></strong>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

app/views/friends/_form.html.erb
<%= form_with(model: friend, local: true) do |form| %>
  <% if friend.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>
      <ul>
        <% friend.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field form-group">
    <%# <%= form.label :first_name %>
    <div class="input-group mb-2 mr-sm-2">
      <div class="input-group-prepend">
        <div class="input-group-text">First Name</div>
      </div>
      <%= form.text_field :first_name, class:"form-control", placeholder: "Your first name" %>
    </div>
  </div>
  <div class="field form-group">
    <%# <%= form.label :last_name %>
    <div class="input-group mb-2 mr-sm-2">
      <div class="input-group-prepend">
        <div class="input-group-text">Last Name</div>
      </div>
      <%= form.text_field :last_name, class:"form-control", placeholder: "Your last name" %>
    </div>
    <div class="field form-group">
      <%# <%= form.label :email %>
      <div class="input-group mb-2 mr-sm-2">
        <div class="input-group-prepend">
          <div class="input-group-text">@</div>
        </div>
        <%= form.text_field :email, class:"form-control", placeholder: "Your last email" %>
      </div>
      <div class="field form-group">
        <%# <%= form.label :phone %>
        <div class="input-group mb-2 mr-sm-2">
          <div class="input-group-prepend">
            <div class="input-group-text">Phone</div>
          </div>
          <%= form.text_field :phone, class:"form-control", placeholder: "Your phone number" %>
        </div>
        <div class="field form-group">
          <%# <%= form.label :twitter %>
          <div class="input-group mb-2 mr-sm-2">
            <div class="input-group-prepend">
              <div class="input-group-text">Twitter</div>
            </div>
            <%= form.text_field :twitter, class:"form-control", placeholder: "Your twitter handle" %>
          </div>
          <div class="input-group mb-2 mr-sm-2">
            <%# <div class="input-group-prepend">
              <div class="input-group-text">User</div>
            </div> %>
            <%= form.number_field :user_id, id: :friend_user_id, class:"form-control", value: current_user.id, type: :hidden %>
          </div>
          <div class="actions">
            <%= form.submit class:"btn btn-success btn-block text-white" %>
          </div>
        <% end %>

app/views/friends/edit.html.erb
<%# <%= render 'form', friend: @friend %>
<div class="d-flex justify-content-center align-items-center">
  <div class="card text-center" style="width: 28rem;">
    <div class="card-header">
      <h1>Editing Friend</h1>
    </div>
    <div class="card-body">
      <%= render 'form', friend: @friend %>
    </div>
    <div class="card-footer text-muted">
      <%= link_to 'Show', @friend, class:"btn btn-warning text-white" %> |
      <%= link_to 'Back', friends_path, class:"btn btn-info text-white" %>
    </div>
  </div>
</div>

app/views/friends/index.html.erb
<%# <p id="notice"><%= notice %></p>
<% if user_signed_in? %>
  <h1>Friends List</h1>
  <table class="table table-striped table-bordered table-hover">
    <thead class="table-dark">
      <tr>
        <th>First name</th>
        <th>Last name</th>
        <th>Email</th>
        <th>Phone</th>
        <th>Twitter</th>
        <th>Created By</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @friends.each do |friend| %>
        <tr>
          <td><%= friend.first_name %></td>
          <td><%= friend.last_name %></td>
          <td><%= friend.email %></td>
          <td><%= friend.phone %></td>
          <td><%= friend.twitter %></td>
          <% if friend.user %>
            <td><%= friend.user.email %></td>
          <% else %>
            <td>Sign in to see</td>
          <% end %>
          <td><%= link_to 'Show', friend %></td>
          <td><%= link_to 'Edit', edit_friend_path(friend), class:"btn btn-success text-white" %></td>
          <td><%= link_to 'Destroy', friend, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-outline-danger' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <br>
  <%= link_to 'Add New Friend', new_friend_path, class:"btn btn-warning text-white" %>
<% else %>
  <h1>Home#index</h1>
  <p>Hello, welcome to the home page</p>
<% end %>

app/views/friends/new.html.erb
<div class="d-flex justify-content-center align-items-center">
  <div class="card text-center" style="width: 28rem;">
    <div class="card-header">
      <h1>Add New Friend</h1>
    </div>
    <div class="card-body">
      <%= render 'form', friend: @friend %>
    </div>
    <div class="card-footer text-muted">
      <%= link_to 'Back', friends_path %>
    </div>
  </div>
</div>

app/views/friends/show.html.erb
<%# <p id="notice"><%= notice %></p>
<div class="jumbotron">
  <h1 class="display-4">
    <%= @friend.first_name %>   <%= @friend.last_name %></h1>
  <p class="lead"><strong>Email:</strong>
    <%= @friend.email %></p>
  <hr class="my-4">
  <p> <strong>Phone:</strong>
    <%= @friend.phone %></p>
  <p>
    <strong>Twitter:</strong>
    <%= @friend.twitter %>
  </p>
  <%= link_to 'Edit', edit_friend_path(@friend), class:"btn btn-info text-white" %> |
  <%= link_to 'Back', friends_path, class:"btn btn-warning text-white" %>
</div>

app/views/home/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-success">
  <a class="navbar-brand font-weight-bold" href="#">FLS</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "Home Page", root_path, class:"nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "About Us", home_about_path, class:"nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Friends list", friends_path, class:"nav-link" %>
      </li>
    </ul>
    <ul class="navbar-nav my-2 my-lg-0">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "Add Friend", new_friend_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Edit Profile", edit_user_registration_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class:"nav-link" %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Sign Up",  new_user_registration_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Login",  new_user_session_path, class:"nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About page</h1>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <title>Friends List</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
  </head>
  <body>
    <%= render 'home/navbar' %>
    <div class="container">
      <br/>
      <% if notice %>
        <%= render 'friends/alerts' %>
      <%end%>
      <%= yield %>
    </div>
  </body>
</html>